apiVersion: apps/v1
kind: Deployment
metadata:
  name: gkd-producer
spec:
  selector:
    matchLabels:
      app: gkd-producer
  replicas: 1
  template:
    metadata:
      labels:
        app: gkd-producer
    spec:
      containers:
        - name: gkd-producer
          image: grpc-k8s-db/gkd-producer:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: gkd-producer-svc
spec:
  selector:
    app: gkd-producer # APP!!! NOT TYPE!!!
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort