apiVersion: apps/v1
kind: Deployment
metadata:
  name: gkd-consumer
spec:
  selector:
    matchLabels:
      app: gkd-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: gkd-consumer
    spec:
      containers:
        - name: gkd-consumer
          image: grpc-k8s-db/gkd-consumer:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
            - containerPort: 35070
---

apiVersion: v1
kind: Service
metadata:
  name: gkd-consumer-svc
spec:
  selector:
    app: gkd-consumer # APP!!! NOT TYPE!!!
  ports:
    - protocol: TCP
      port: 8080
      name: tcp-80
      targetPort: 8080
    - protocol: TCP
      port: 35070
      name: grpc-35070
      targetPort: 35070
  type: NodePort

# NOTE: Some times in Open Shift, request between services through gRPC could converts to HTTP/1.x and fails because
# of that. It caused by name of port in k8s service configuration. For proper work, use names which starts from 'grpc-'.